---
title: "Class Computing"
author: "Jung-Han Wang"
date: "November 12, 2014"
output: pdf_document
---

This is a practice of Support Vector machine exhibited in Class on 11/12/14

```{r}


library(MASS)

p<-3
n1<-50
n2<-25
a1<-mvrnorm(n1,rep(0,p),diag(p));r1<-rep(1,n1)
a2<-mvrnorm(n2,rep(1,p),diag(p));r2<-rep(-1,n2)

a<-rbind(a1,a2);dim(a)
r<-c(r1,r2)
data<-cbind(r,a)
ind<-sample(1:nrow(data),size=nrow(data),replace=F)
dta<-data[ind,]
x<-dta[,-1];y<-dta[,1]
y

Y<-y; X<-x;
C<-Inf; gamma=1.5; esp=1e-10;

require('quadprog')
rbf_kernel<-function(x1,x2,gamma){
  K<-exp(-gamma*rowSums(x1-x2)^2)  
}

N<-length(Y)
Dm<-matrix(0,N,N)
for(i in 1:N){
  for(j in 1:N){
    Dm[i,j]<-Y[i]*Y[j]*rbf_kernel(matrix(X[i,],1),matrix(X[j,],1),gamma)
    
  }
}

Dm<-Dm+diag(N)*1e-12 #adding a very small number to the diag, some trick
dv<-t(rep(1,N))
meq<-1

Am<-cbind(matrix(Y,N),diag(N))
bv<-rep(0,N+1) # the 1 is for the sum(alpha)

if(C!=Inf){
  #and upper bound is given
  Am<-cbind(Am,-1*diag(N))
  bv<-c(cbind(matrix(bv,1),matrix(rep(-C,N),1)))
}

alpha_org<-solve.QP(Dm,dv,Am,meq=meq,bvec=bv)$solution

indx<-which(alpha_org>esp, arr.ind=TRUE)
alpha<-alpha_org[indx]
nSV<-length(indx)
if(nSV==0){
  throw("QP is not able to give a solution")
}

Xv<-X[indx,]
Yv<-Y[indx]

idv<-which.max(alpha)
b<-Yv[idv]-sum(alpha*Yv*rbf_kernel(Xv,matrix(1,nSV,1)%*%Xv[idv,],gamma))
print(alpha)
print(Xv)
print(b)
print(nSV)
print(Yv)
print(gamma)

```

You can also embed plots, for example:

```{r, echo=FALSE}
plot(cars)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
